# Generated by Django 2.2.4 on 2019-08-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('date_birthaday', models.DateField()),
                ('city_birthday', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('start_work', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positions.Position')),
            ],
        ),
    ]
