# Generated by Django 2.2.4 on 2019-08-14 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=40, null=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
