# Generated by Django 2.2.4 on 2019-08-13 16:05

from django.db import migrations, models
import vacations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

