# Generated by Django 2.2.4 on 2019-08-14 10:11

import departments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20190812_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[departments.validators.validate_only_letters]),
        ),
    ]
